include:
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/packaging.yml'
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/packaging-arm.yml'
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'

stages:
  - pre-package
  - package
  - post-package
  - deploy

docker-build-arm:
  variables:
    DBLD_PARENT_IMAGE_TAG: arm-latest

.deploy:
  environment:
    url: https://${DD_TRAEFIK_DOMAIN}
