version: '3.7'

services:
  index-page:
    image: ${IMAGE_NAME:-pedroetb/index-page}:${IMAGE_TAG:-latest}
    build:
      context: .
      args:
        PARENT_IMAGE_NAME:
        PARENT_IMAGE_TAG:
    environment:
      SITE_PORT:
      SITE_PATH:
    networks:
      - traefik-net
    healthcheck:
      test: wget --spider -q http://localhost:${SITE_PORT}
      interval: ${INDEX_PAGE_HEALTHCHECK_INTERVAL:-30s}
      timeout: ${INDEX_PAGE_HEALTHCHECK_TIMEOUT:-10s}
      retries: ${INDEX_PAGE_HEALTHCHECK_RETRIES:-3}
      start_period: ${INDEX_PAGE_HEALTHCHECK_START_PERIOD:-1m}
    deploy:
      mode: replicated
      replicas: ${INDEX_PAGE_REPLICAS:-1}
      labels:
        traefik.frontend.rule: Host:${INDEX_PAGE_HOSTNAME}
        traefik.backend: index-page
        traefik.port: '${SITE_PORT}'
      restart_policy:
        delay: ${INDEX_PAGE_RESTART_POLICY_DELAY:-10s}
        window: ${INDEX_PAGE_RESTART_POLICY_WINDOW:-1m}
      resources:
        limits:
          cpus: '${INDEX_PAGE_LIMITS_CPUS:-0.5}'
          memory: ${INDEX_PAGE_LIMITS_MEMORY:-32M}
        reservations:
          cpus: '${INDEX_PAGE_RESERVATIONS_CPUS:-0.001}'
          memory: ${INDEX_PAGE_RESERVATIONS_MEMORY:-20M}

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true
