version: '3.7'

services:
  index-page:
    image: pedroetb/index-page:${IMAGE_TAG:-latest}
    networks:
      - traefik-net
    healthcheck:
      test: wget --spider -S -t 3 http://localhost:${PORT}
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.port: "${PORT}"
        traefik.docker.network: traefik-net
        traefik.frontend.rule: Host:${PUBLIC_HOSTNAME}
        traefik.backend: index-page
      restart_policy:
        delay: 10s
        window: 30s
      resources:
        limits:
          cpus: '0.5'
          memory: 32M
        reservations:
          memory: 26M

networks:
  traefik-net:
    external: true
