version: '3.7'

services:
  index-page:
    image: ${IMAGE_NAME:-pedroetb/index-page}:${IMAGE_TAG:-latest}
    build:
      context: ${BUILD_CONTEXT:-.}
      dockerfile: ${DOCKERFILE:-Dockerfile}
      args:
        PARENT_IMAGE_NAME:
        PARENT_IMAGE_TAG:
    environment:
      SITE_PORT:
      SITE_PATH:
    networks:
      traefik-net:
    healthcheck:
      test: wget --spider -q http://localhost:${SITE_PORT}
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-10s}
      retries: ${HEALTHCHECK_RETRIES:-10}
      start_period: ${HEALTHCHECK_START_PERIOD:-1m}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-3s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      labels:
        traefik.http.routers.index-page-redirect.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.index-page-redirect.tls.certresolver: ${TRAEFIK_CERTRESOLVER}
        traefik.http.routers.index-page-redirect.rule: PathPrefix(`/`)
        traefik.http.middlewares.index-page-redirectregex.redirectregex.regex: .*
        traefik.http.middlewares.index-page-redirectregex.redirectregex.replacement: https://${TRAEFIK_DOMAIN}
        traefik.http.routers.index-page-redirect.middlewares: index-page-redirectregex

        traefik.http.routers.index-page.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.index-page.tls.certresolver: ${TRAEFIK_CERTRESOLVER}
        traefik.http.routers.index-page.rule: Host(`${TRAEFIK_DOMAIN}`)
        traefik.http.services.index-page.loadbalancer.server.port: ${SITE_PORT}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${RESOURCES_LIMITS_MEMORY:-32M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-20M}

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true
