version: '3.7'

services:
  index-page:
    image: pedroetb/index-page:${IMAGE_TAG:-latest}
    environment:
      - SITE_PORT
      - SITE_PATH
    networks:
      - traefik-net
    healthcheck:
      test: wget --spider -nv -t 3 http://localhost:${SITE_PORT}
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.frontend.rule: Host:${PUBLIC_HOSTNAME}
        traefik.backend: index-page
        traefik.port: "${SITE_PORT}"
      restart_policy:
        delay: 10s
        window: 30s
      resources:
        limits:
          cpus: "${INDEX_PAGE_LIMITS_CPUS}"
          memory: ${INDEX_PAGE_LIMITS_MEMORY}
        reservations:
          memory: ${INDEX_PAGE_RESERVATIONS_MEMORY}

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true
