version: '3.7'

services:
  index-page:
    image: pedroetb/index-page:${IMAGE_TAG:-latest}
    environment:
      - SITE_PORT
      - SITE_PATH
    networks:
      - traefik-net
    healthcheck:
      test: wget --spider -nv -t 3 http://localhost:${SITE_PORT}
      interval: ${INDEX_PAGE_HEALTHCHECK_INTERVAL}
      timeout: ${INDEX_PAGE_HEALTHCHECK_TIMEOUT}
      retries: ${INDEX_PAGE_HEALTHCHECK_RETRIES}
      start_period: ${INDEX_PAGE_HEALTHCHECK_START_PERIOD}
    deploy:
      mode: replicated
      replicas: ${INDEX_PAGE_REPLICAS}
      labels:
        traefik.frontend.rule: Host:${INDEX_PAGE_HOSTNAME}
        traefik.backend: index-page
        traefik.port: "${SITE_PORT}"
      restart_policy:
        delay: ${INDEX_PAGE_RESTART_POLICY_DELAY}
        window: ${INDEX_PAGE_RESTART_POLICY_WINDOW}
      resources:
        limits:
          cpus: "${INDEX_PAGE_LIMITS_CPUS}"
          memory: ${INDEX_PAGE_LIMITS_MEMORY}
        reservations:
          memory: ${INDEX_PAGE_RESERVATIONS_MEMORY}

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true
